/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmp_gui;

import java.util.ArrayList;
import java.lang.NumberFormatException;
import java.lang.IndexOutOfBoundsException;
/**
 *
 * @author John
 */


public class Addition_Promithies_Medicine extends javax.swing.JFrame {

    /**
     * Creates new form Addition_Promithies_Medicine
     */
    private int available_space;
    private ArrayList<String> medList = new ArrayList();
    private ArrayList<String> medEqList = new ArrayList();
    private ArrayList<String> medQuantityList = new ArrayList();
    private ArrayList<String> medEqQuantityList = new ArrayList();
    
    public Addition_Promithies_Medicine() {
        initComponents();
    }
    public Addition_Promithies_Medicine(int available_space,ArrayList<String> medList,ArrayList<String> medEqList,ArrayList<String> medQuantityList,ArrayList<String> medEqQuantityList) {
        this.available_space = available_space;
        this.medList = medList;
        this.medEqList = medEqList;
        this.medQuantityList = medQuantityList;
        this.medEqQuantityList = medEqQuantityList;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        condMsg = new javax.swing.JPanel();
        nameTag = new javax.swing.JTextField();
        quantityTag = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        condMsg.setBackground(new java.awt.Color(153, 204, 255));

        nameTag.setForeground(new java.awt.Color(153, 153, 153));
        nameTag.setText("Όνομα προμήθειας");

        quantityTag.setForeground(new java.awt.Color(153, 153, 153));
        quantityTag.setText("Ποσότητα");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        backButton.setText("Τέλος");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout condMsgLayout = new javax.swing.GroupLayout(condMsg);
        condMsg.setLayout(condMsgLayout);
        condMsgLayout.setHorizontalGroup(
            condMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(condMsgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(condMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityTag, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTag, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, condMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(31, 31, 31))
        );
        condMsgLayout.setVerticalGroup(
            condMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(condMsgLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(nameTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(quantityTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(condMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(backButton))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(condMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(condMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Dashboard_Promithies dp = new Dashboard_Promithies(available_space,medList,medEqList,medEqQuantityList,medEqQuantityList);
        Conditional_Message cm = new Conditional_Message(dp);
        try{
        String medName = nameTag.getText();
        int quantity = Integer.parseInt(quantityTag.getText());
        if (available_space - quantity < 0){
            throw new java.lang.IndexOutOfBoundsException();
        }
        available_space = available_space - quantity;
        medList.add("Medicine Name: " + medName + "     Quantity: " + quantity);
        medQuantityList.add(Integer.toString(quantity));
        cm.triggerMsg("Επιτυχής προσθήκη!");
        cm.setVisible(true);
        } 
        catch(java.lang.NumberFormatException exc){
            cm.triggerMsg("<html>Η προσθήκη απέτυχε!&nbsp;&nbsp;Παρακαλώ ελέγξτε αν τα στοιχεία που δώσατε&nbsp;&nbsp;είναι σωστά και δοκιμάστε ξανά!</html>");
            cm.setVisible(true);
        } catch (java.lang.IndexOutOfBoundsException e){
            cm.triggerMsg("Exceeded maximum space!");
            cm.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Dashboard_Promithies dp = new Dashboard_Promithies(available_space, medList,medEqList,medQuantityList,medEqQuantityList);
        dispose();
        dp.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addition_Promithies_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addition_Promithies_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addition_Promithies_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addition_Promithies_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addition_Promithies_Medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel condMsg;
    private javax.swing.JTextField nameTag;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField quantityTag;
    // End of variables declaration//GEN-END:variables
}
