/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmp_gui;

import java.util.ArrayList;

/**
 *
 * @author John
 */
public class Conditional_Message_Promithies_MedEq extends javax.swing.JFrame {

    /**
     * Creates new form Conditional_Message_Promithies_MedEq
     */
    private ArrayList<String> medEqList = new ArrayList();
    private ArrayList<String> medList = new ArrayList();
    private ArrayList<String> medQuantityList = new ArrayList();
    private ArrayList<String> medEqQuantityList = new ArrayList();
    private int available_space;
    public Conditional_Message_Promithies_MedEq() {
        initComponents();
    }
    public Conditional_Message_Promithies_MedEq(int available_space,ArrayList<String> medList, ArrayList<String> medEqList,ArrayList<String> medQuantityList,ArrayList<String> medEqQuantityList) {
        this.available_space = available_space;
        this.medEqList = medEqList;
        this.medList = medList;
        this.medEqQuantityList = medEqQuantityList;
        this.medQuantityList = medEqQuantityList;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        condMsg = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        infoTag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        condMsg.setBackground(new java.awt.Color(153, 204, 255));

        addButton.setText("Προσθήκη Ιατρικού εξοπλισμού");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Διαγραφή Ιατρικού εξοπλισμού");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        infoTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        infoTag.setForeground(new java.awt.Color(255, 255, 255));
        infoTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoTag.setText("<html>Μπορείτε να προχωρήσετε σε προσθήκη ή<br>&nbsp;&nbsp;&nbsp;&nbsp;διαγραφή του ιατρικού εξοπλισμού</html>");
        infoTag.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        javax.swing.GroupLayout condMsgLayout = new javax.swing.GroupLayout(condMsg);
        condMsg.setLayout(condMsgLayout);
        condMsgLayout.setHorizontalGroup(
            condMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(condMsgLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(infoTag, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(condMsgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addGap(55, 55, 55))
        );
        condMsgLayout.setVerticalGroup(
            condMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, condMsgLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(infoTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(condMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(condMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(condMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Addition_Promithies_MedEq apm = new Addition_Promithies_MedEq(available_space,medList,medEqList,medQuantityList,medEqQuantityList);
        dispose();
        apm.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        Deletion_Promithies_MedEq dpm = new Deletion_Promithies_MedEq(available_space,medList,medEqList,medQuantityList,medEqQuantityList);
        dispose();
        dpm.setVisible(true);
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conditional_Message_Promithies_MedEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conditional_Message_Promithies_MedEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conditional_Message_Promithies_MedEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conditional_Message_Promithies_MedEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conditional_Message_Promithies_MedEq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel condMsg;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel infoTag;
    // End of variables declaration//GEN-END:variables
}
