package hmp_gui;

import java.sql.*;  
import java.util.ArrayList;
import java.util.Arrays;
import data.Epimelitis;
import data.Clinic;
import data.Patient;



/**
 *
 * @author Nikolaos Skamnelos
 */
public class Dashboard_Epimelitis extends javax.swing.JFrame {
    
    
        Epimelitis epimelitis = new Epimelitis();
    /**
     * Creates new form Dashboard
     */
    public Dashboard_Epimelitis() {
        initComponents(); 
        Settings();
        this.getAmkaDB();
        
    }
    public void Settings(){
        Patient_Scroll.setVisible(false);
        Patient_Jlist.setVisible(false);
        permission_error_msg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard_Layer = new javax.swing.JLayeredPane();
        Button_Panel = new javax.swing.JPanel();
        logout_button = new javax.swing.JButton();
        Tab_Panel = new javax.swing.JPanel();
        Dashboard_tabs = new javax.swing.JTabbedPane();
        user_info = new javax.swing.JPanel();
        applications = new javax.swing.JPanel();
        patient_list = new javax.swing.JPanel();
        Patient_Scroll = new javax.swing.JScrollPane();
        Patient_Jlist = new javax.swing.JList<>();
        this.InitPatientList();
        SelectPatButton = new javax.swing.JButton();
        permission_error_msg = new javax.swing.JLabel();
        permission_error_msg.setVisible(false);
        clinic_info = new javax.swing.JPanel();
        eidik_comments = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setLocationByPlatform(true);

        Dashboard_Layer.setBackground(new java.awt.Color(153, 204, 255));
        Dashboard_Layer.setForeground(new java.awt.Color(153, 204, 255));

        logout_button.setBackground(new java.awt.Color(255, 0, 0));
        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Button_PanelLayout = new javax.swing.GroupLayout(Button_Panel);
        Button_Panel.setLayout(Button_PanelLayout);
        Button_PanelLayout.setHorizontalGroup(
            Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_PanelLayout.createSequentialGroup()
                .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Button_PanelLayout.setVerticalGroup(
            Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Button_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout_button))
        );

        Dashboard_tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Dashboard_tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Dashboard_tabsStateChanged(evt);
            }
        });

        user_info.setBackground(new java.awt.Color(153, 204, 255));
        user_info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout user_infoLayout = new javax.swing.GroupLayout(user_info);
        user_info.setLayout(user_infoLayout);
        user_infoLayout.setHorizontalGroup(
            user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        user_infoLayout.setVerticalGroup(
            user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        Dashboard_tabs.addTab("<html>Πληροφορίες<br>&nbsp;&nbsp;&nbsp; Χρήστη</html>", user_info);

        applications.setBackground(new java.awt.Color(153, 204, 255));
        applications.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout applicationsLayout = new javax.swing.GroupLayout(applications);
        applications.setLayout(applicationsLayout);
        applicationsLayout.setHorizontalGroup(
            applicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        applicationsLayout.setVerticalGroup(
            applicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        Dashboard_tabs.addTab("Αιτήσεις", applications);

        patient_list.setBackground(new java.awt.Color(153, 204, 255));
        patient_list.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        Patient_Jlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Arrays.stream(epimelitis.getPatientList()).mapToObj(String::valueOf).toArray(String[]::new);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Patient_Scroll.setViewportView(Patient_Jlist);

        SelectPatButton.setText("Επιλογή");
        SelectPatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectPatButtonActionPerformed(evt);
            }
        });

        permission_error_msg.setBackground(new java.awt.Color(102, 153, 255));
        permission_error_msg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        permission_error_msg.setForeground(new java.awt.Color(255, 0, 0));
        permission_error_msg.setText("<html>Δεν έχετε άδεια να δείτε τα στοιχεία αυτού του Ασθενή... <br>Επιλέξτε κάποιον άλλον.</html>");

        javax.swing.GroupLayout patient_listLayout = new javax.swing.GroupLayout(patient_list);
        patient_list.setLayout(patient_listLayout);
        patient_listLayout.setHorizontalGroup(
            patient_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_listLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(patient_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(patient_listLayout.createSequentialGroup()
                        .addComponent(permission_error_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectPatButton))
                    .addComponent(Patient_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        patient_listLayout.setVerticalGroup(
            patient_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patient_listLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(Patient_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patient_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectPatButton)
                    .addComponent(permission_error_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        Dashboard_tabs.addTab("Λίστα Ασθενών", patient_list);

        clinic_info.setBackground(new java.awt.Color(153, 204, 255));
        clinic_info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout clinic_infoLayout = new javax.swing.GroupLayout(clinic_info);
        clinic_info.setLayout(clinic_infoLayout);
        clinic_infoLayout.setHorizontalGroup(
            clinic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        clinic_infoLayout.setVerticalGroup(
            clinic_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        Dashboard_tabs.addTab("<html>Πληροφορίες<br>&nbsp;&nbsp;&nbsp;&nbsp; Κλινικής</html>", clinic_info);

        eidik_comments.setBackground(new java.awt.Color(153, 204, 255));
        eidik_comments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout eidik_commentsLayout = new javax.swing.GroupLayout(eidik_comments);
        eidik_comments.setLayout(eidik_commentsLayout);
        eidik_commentsLayout.setHorizontalGroup(
            eidik_commentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        eidik_commentsLayout.setVerticalGroup(
            eidik_commentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        Dashboard_tabs.addTab("<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Λίστα<br> Ειδικευόμενων</html>", eidik_comments);

        javax.swing.GroupLayout Tab_PanelLayout = new javax.swing.GroupLayout(Tab_Panel);
        Tab_Panel.setLayout(Tab_PanelLayout);
        Tab_PanelLayout.setHorizontalGroup(
            Tab_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        Tab_PanelLayout.setVerticalGroup(
            Tab_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Dashboard_tabs.getAccessibleContext().setAccessibleParent(Dashboard_tabs);

        Dashboard_Layer.setLayer(Button_Panel, 2);
        Dashboard_Layer.setLayer(Tab_Panel, 1);

        javax.swing.GroupLayout Dashboard_LayerLayout = new javax.swing.GroupLayout(Dashboard_Layer);
        Dashboard_Layer.setLayout(Dashboard_LayerLayout);
        Dashboard_LayerLayout.setHorizontalGroup(
            Dashboard_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard_LayerLayout.createSequentialGroup()
                .addComponent(Button_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 600, Short.MAX_VALUE))
            .addGroup(Dashboard_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Tab_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dashboard_LayerLayout.setVerticalGroup(
            Dashboard_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dashboard_LayerLayout.createSequentialGroup()
                .addGap(0, 454, Short.MAX_VALUE)
                .addComponent(Button_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Dashboard_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Tab_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_Layer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_Layer)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Otan ginete logout kanei clear to token pou deixnei to eidos xrhsth
    private void clearTokens(){
        Login.epimelitis_counter = false;
    }
    
    //Logout Function
    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
       
        clearTokens();
        dispose();
        Login login_page = new Login();
        login_page.setVisible(true);
        
    }//GEN-LAST:event_logout_buttonActionPerformed

    //An epilektei h 2h kartela na kanei diplay
    private void Dashboard_tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Dashboard_tabsStateChanged
        if(Dashboard_tabs.getSelectedIndex()==2) 
            {
                this.displayPatListMenu();
            }
    }//GEN-LAST:event_Dashboard_tabsStateChanged

    //Otan patiete to koumpi pairnei to Selected Value apo th lista kai kanei checkDocPermisions()
    private void SelectPatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectPatButtonActionPerformed
        Object Pat_Jlist_Value = Patient_Jlist.getSelectedValue();
        String Pat_Jlist_Str = Pat_Jlist_Value.toString();
        Patient patient = new Patient();
        
        
        //get his values from the Database
       /* try{  
           //connect to the MySQL Database
        Class.forName("com.mysql.jdbc.Driver");  
        Connection connection=DriverManager.getConnection(  
        "jdbc:mysql://localhost:3306/sonoo","root","root");    
        
        //create the statement to get the AMKA
        Statement stmt3=connection.createStatement();  
        ResultSet rs2=stmt3.executeQuery("select * from patient where amka=... ");  
        while(rs2.next()){
            patient.setSupervisedBy(rs2.getInt("amka"));     
        }          
        //Closing Connection
        connection.close();  
        }
       catch(Exception e){ System.out.println(e);}  */
       
       //boolean can_check = patient.CheckDocPermissions(patient.getSupervisedBy().getAMKA(),"Check");
       boolean can_check = true;
       if (can_check){
           Patient_Profile PatientProfile = new Patient_Profile();
           PatientProfile.setVisible(true);
       }
       else permission_error_msg.setVisible(true);
    }//GEN-LAST:event_SelectPatButtonActionPerformed
    
    //Gia na paroume to Amka tou giatrou
    public void getAmkaDB(){
        
       epimelitis.setAMKA(1234567);
       /*try{  
           //connect to the MySQL Database
        Class.forName("com.mysql.jdbc.Driver");  
        Connection connection=DriverManager.getConnection(  
        "jdbc:mysql://localhost:3306/sonoo","root","root");    
        
        //create the statement to get the AMKA
        Statement stmt1=connection.createStatement();  
        ResultSet rs1=stmt1.executeQuery("select amka from doctor where amka=... ");  
        while(rs1.next()){
            epimelitis.setAMKA(rs1.getInt("amka"));     
        }          
        //Closing Connection
        connection.close();  
        }
       catch(Exception e){ System.out.println(e);}  */
    }
    
    //Gia na paroume to Patient List tou giatrou
    public void InitPatientList(){
        int[] tempArray={1,23,4,5,67,5};
        epimelitis.setPatientList(tempArray);
       /* try{  
           //connect to the MySQL Database
        Class.forName("com.mysql.jdbc.Driver");  
        Connection connection=DriverManager.getConnection(  
        "jdbc:mysql://localhost:3306/sonoo","root","root");   
        
        //create the Statment to get the Patients
        Statement stmt2=connection.createStatement(); 
        ResultSet rs2=stmt2.executeQuery("select patient_amka from ... where doctor_amka=... ");  
        
        //to store the patients
        ArrayList<Integer> PatList = new ArrayList<Integer>();
        
        //storing the patients from the database
        while(rs2.next()){
            PatList.add(rs2.getInt("patient_amka"));        
        }
        
        //Converting PatList to array of integers
        int[] tempArray = new int[PatList.size()];  
        for (int i=0; i < tempArray.length; i++){
        tempArray[i] = PatList.get(i).intValue();
        }
        
        //Setting the patient_list
        epimelitis.setPatientList(tempArray);
        
        //Converting the patient_list to a string list for the Patient_JList
        String Patient_AMKA_Str[] = Arrays.stream(epimelitis.getPatientList()).mapToObj(String::valueOf).toArray(String[]::new);
        
        //Closing Connection
        connection.close(); 
       
        }
       catch(Exception e){ System.out.println(e);}  */
    }
    
    //Kanei Display to Patient Menu
    public void displayPatListMenu(){
        Patient_Jlist.setVisible(true);
        Patient_Scroll.setVisible(true);
        permission_error_msg.setVisible(false);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Epimelitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Epimelitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Epimelitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Epimelitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Dashboard_Epimelitis().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button_Panel;
    private javax.swing.JLayeredPane Dashboard_Layer;
    private javax.swing.JTabbedPane Dashboard_tabs;
    private javax.swing.JList<String> Patient_Jlist;
    private javax.swing.JScrollPane Patient_Scroll;
    private javax.swing.JButton SelectPatButton;
    private javax.swing.JPanel Tab_Panel;
    private javax.swing.JPanel applications;
    private javax.swing.JPanel clinic_info;
    private javax.swing.JPanel eidik_comments;
    private javax.swing.JButton logout_button;
    private javax.swing.JPanel patient_list;
    private javax.swing.JLabel permission_error_msg;
    private javax.swing.JPanel user_info;
    // End of variables declaration//GEN-END:variables

}
