/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmp_gui;
import data.Patient;
import data.Doctor;
import java.util.ArrayList;
/**
 *
 * @author Nikos
 */
public class Dashboard_Gramateia extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Gramateia
     */
    private ArrayList<String> Patient_List = new ArrayList();
    private ArrayList<String> Doctor_List = new ArrayList();
    Doctor doc = new Doctor();
    private ArrayList<Patient> pat = new ArrayList();
    private ArrayList<Doctor> dr = new ArrayList();
    
    public Dashboard_Gramateia(ArrayList<Patient> patient,ArrayList<Doctor> doctor) {
       this.dr = doctor;
       this.pat = patient;
        initComponents();
        //Patient_List.add(Temp.getName());
        
    }
     public Dashboard_Gramateia() {
       
        initComponents();
    }    
     
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard_Layer = new javax.swing.JLayeredPane();
        Button_Panel = new javax.swing.JPanel();
        logout_button = new javax.swing.JButton();
        Tab_Panel = new javax.swing.JPanel();
        Dashboard_tabs = new javax.swing.JTabbedPane();
        staff_list = new javax.swing.JPanel();
        Patient_Addition = new javax.swing.JButton();
        Patient_Deletion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Personnel_List_Grammateia = new javax.swing.JList<>();
        this.Add_Doctor();
        Personnel_Addition = new javax.swing.JButton();
        Personnel_Deletion = new javax.swing.JButton();
        Label_Patient_List = new javax.swing.JLabel();
        Label_Personnel_List = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Patient_List_Grammateia = new javax.swing.JList<>();
        documents = new javax.swing.JPanel();
        user_info = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setLocationByPlatform(true);

        Dashboard_Layer.setBackground(new java.awt.Color(153, 204, 255));
        Dashboard_Layer.setForeground(new java.awt.Color(153, 204, 255));

        logout_button.setBackground(new java.awt.Color(255, 0, 0));
        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Button_PanelLayout = new javax.swing.GroupLayout(Button_Panel);
        Button_Panel.setLayout(Button_PanelLayout);
        Button_PanelLayout.setHorizontalGroup(
            Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_PanelLayout.createSequentialGroup()
                .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Button_PanelLayout.setVerticalGroup(
            Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Button_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout_button))
        );

        Dashboard_tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        staff_list.setBackground(new java.awt.Color(153, 204, 255));
        staff_list.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        Patient_Addition.setText("Προσθήκη ασθενή");
        Patient_Addition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Patient_AdditionMouseClicked(evt);
            }
        });
        Patient_Addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_AdditionActionPerformed(evt);
            }
        });

        Patient_Deletion.setText("Διαγραφή ασθενή");
        Patient_Deletion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Patient_DeletionMouseClicked(evt);
            }
        });
        Patient_Deletion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_DeletionActionPerformed(evt);
            }
        });

        Personnel_List_Grammateia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Personnel_List_Grammateia.setModel(new javax.swing.DefaultListModel<String>());
        {
            javax.swing.DefaultListModel<String> docList = (javax.swing.DefaultListModel<String>)Personnel_List_Grammateia.getModel();
            for(int i=0; i<Doctor_List.size(); i++){
                docList.addElement(Doctor_List.get(i));
            }
        }
        jScrollPane2.setViewportView(Personnel_List_Grammateia);

        Personnel_Addition.setText("Προσθήκη προσωπικού");
        Personnel_Addition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Personnel_AdditionMouseClicked(evt);
            }
        });

        Personnel_Deletion.setText("Διαγραφή προσωπικού");
        Personnel_Deletion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Personnel_DeletionMouseClicked(evt);
            }
        });
        Personnel_Deletion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personnel_DeletionActionPerformed(evt);
            }
        });

        Label_Patient_List.setText("Λίστα Ασθενών");

        Label_Personnel_List.setText("Λίστα Προσωπικού");

        this.Add_Patient();
        Patient_List_Grammateia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Patient_List_Grammateia.setModel(new javax.swing.DefaultListModel<String>()
        );
        { javax.swing.DefaultListModel<String> PList = (javax.swing.DefaultListModel<String>)Patient_List_Grammateia.getModel();
            for (int i = 0; i < Patient_List.size(); i++){
                PList.addElement(Patient_List.get(i));
            }

        }
        jScrollPane1.setViewportView(Patient_List_Grammateia);

        javax.swing.GroupLayout staff_listLayout = new javax.swing.GroupLayout(staff_list);
        staff_list.setLayout(staff_listLayout);
        staff_listLayout.setHorizontalGroup(
            staff_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_listLayout.createSequentialGroup()
                .addGroup(staff_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staff_listLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Label_Patient_List, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staff_listLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(staff_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(staff_listLayout.createSequentialGroup()
                                .addComponent(Patient_Addition)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Patient_Deletion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(staff_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staff_listLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(staff_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(staff_listLayout.createSequentialGroup()
                                .addComponent(Personnel_Addition, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Personnel_Deletion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staff_listLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_Personnel_List, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        staff_listLayout.setVerticalGroup(
            staff_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_listLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staff_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Patient_List, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Personnel_List, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(staff_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staff_listLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(staff_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Patient_Deletion)
                            .addComponent(Patient_Addition)
                            .addComponent(Personnel_Addition)
                            .addComponent(Personnel_Deletion))
                        .addGap(95, 95, 95))
                    .addGroup(staff_listLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Dashboard_tabs.addTab("<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Πρόσβαση<br>&nbsp;&nbsp;&nbsp;&nbsp;σε πληροφορίες<br>προσωπικού/ασθενών</html>", staff_list);

        documents.setBackground(new java.awt.Color(153, 204, 255));
        documents.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout documentsLayout = new javax.swing.GroupLayout(documents);
        documents.setLayout(documentsLayout);
        documentsLayout.setHorizontalGroup(
            documentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        documentsLayout.setVerticalGroup(
            documentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        Dashboard_tabs.addTab("<html>&nbsp;&nbsp;Έκδοση<br> Εγγράφων</html>", documents);

        user_info.setBackground(new java.awt.Color(153, 204, 255));
        user_info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout user_infoLayout = new javax.swing.GroupLayout(user_info);
        user_info.setLayout(user_infoLayout);
        user_infoLayout.setHorizontalGroup(
            user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        user_infoLayout.setVerticalGroup(
            user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        Dashboard_tabs.addTab("<html>Πληροφορίες<br>&nbsp;&nbsp;&nbsp; Χρήστη</html>", user_info);

        javax.swing.GroupLayout Tab_PanelLayout = new javax.swing.GroupLayout(Tab_Panel);
        Tab_Panel.setLayout(Tab_PanelLayout);
        Tab_PanelLayout.setHorizontalGroup(
            Tab_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_tabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 695, Short.MAX_VALUE)
        );
        Tab_PanelLayout.setVerticalGroup(
            Tab_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Dashboard_Layer.setLayer(Button_Panel, 2);
        Dashboard_Layer.setLayer(Tab_Panel, 1);

        javax.swing.GroupLayout Dashboard_LayerLayout = new javax.swing.GroupLayout(Dashboard_Layer);
        Dashboard_Layer.setLayout(Dashboard_LayerLayout);
        Dashboard_LayerLayout.setHorizontalGroup(
            Dashboard_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard_LayerLayout.createSequentialGroup()
                .addComponent(Button_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 728, Short.MAX_VALUE))
            .addGroup(Dashboard_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Tab_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dashboard_LayerLayout.setVerticalGroup(
            Dashboard_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dashboard_LayerLayout.createSequentialGroup()
                .addGap(0, 348, Short.MAX_VALUE)
                .addComponent(Button_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Dashboard_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Tab_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_Layer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_Layer)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     //Otan ginete logout kanei clear to token pou deixnei to eidos xrhsth
    private void clearTokens(){
        Login.gramateia_counter = false;     
    }
    public void getAmka(){
        doc.setAMKA(5);
    }
    
    public void Add_Patient(){
        
        //pat.add(Temp);
        int i;
        Doctor temp;
        Patient_List.clear();
        for (i=0; i<pat.size(); i++){
            temp = pat.get(i).getSupervisedBy();
            this.Patient_List.add("Name: " + pat.get(i).getName() + "   Age: " + pat.get(i).getAge() + "    Patient_History: " + pat.get(i).getHistory() + "    Patient Condition: " + pat.get(i).getConditions() + "   Supervised by: " + temp.getName() + "    Status: " + pat.get(i).getStatus());
        }
    }
    
    public void Add_Doctor(){
        
        //pat.add(Temp);
        int i;
        Doctor_List.clear();
        for (i=0; i<dr.size(); i++){
            dr.get(i).setPatientList(pat);
            this.Doctor_List.add("Doctor name: " + dr.get(i).getName() + "  AMKA: " + dr.get(i).getAMKA() + "   Speciality: " + dr.get(i).getSpeciality() + "   Clinic " + dr.get(i).getClinicName());
        }
    }
    //Logout Function
    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed

        clearTokens();
        dispose();
        Login login_page = new Login();
        login_page.setVisible(true);

    }//GEN-LAST:event_logout_buttonActionPerformed

    private void Patient_AdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_AdditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_AdditionActionPerformed

    private void Patient_AdditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_AdditionMouseClicked
    Patient_Addition_Gramateia Patient_Add = new Patient_Addition_Gramateia(pat,dr);
    Patient_Add.setVisible(true);
    dispose();
            // TODO add your handling code here:
    }//GEN-LAST:event_Patient_AdditionMouseClicked

    private void Personnel_AdditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personnel_AdditionMouseClicked
    Personnel_Addition_Gramateia   Personnel_Add = new Personnel_Addition_Gramateia(pat,dr);
    Personnel_Add.setVisible(true);
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Personnel_AdditionMouseClicked

    private void Patient_DeletionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_DeletionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_DeletionActionPerformed

    private void Patient_DeletionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_DeletionMouseClicked
    Patient_Deletion_Gramateia Patient_Deletion = new Patient_Deletion_Gramateia(pat,dr);
    Patient_Deletion.setVisible(true);
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_DeletionMouseClicked

    private void Personnel_DeletionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personnel_DeletionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Personnel_DeletionActionPerformed

    private void Personnel_DeletionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personnel_DeletionMouseClicked
    Personnel_Deletion_Gramateia Personnel_Deletion = new Personnel_Deletion_Gramateia(pat,dr);
    Personnel_Deletion.setVisible(true);
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Personnel_DeletionMouseClicked

    /**
     * @param args the command line arguments
     */
    
    //na kanw define thn init sunarthsh
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Gramateia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Gramateia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Gramateia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Gramateia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Gramateia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button_Panel;
    private javax.swing.JLayeredPane Dashboard_Layer;
    private javax.swing.JTabbedPane Dashboard_tabs;
    private javax.swing.JLabel Label_Patient_List;
    private javax.swing.JLabel Label_Personnel_List;
    private javax.swing.JButton Patient_Addition;
    private javax.swing.JButton Patient_Deletion;
    private javax.swing.JList<String> Patient_List_Grammateia;
    private javax.swing.JButton Personnel_Addition;
    private javax.swing.JButton Personnel_Deletion;
    private javax.swing.JList<String> Personnel_List_Grammateia;
    private javax.swing.JPanel Tab_Panel;
    private javax.swing.JPanel documents;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout_button;
    private javax.swing.JPanel staff_list;
    private javax.swing.JPanel user_info;
    // End of variables declaration//GEN-END:variables
}
