/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmp_gui;

import java.util.ArrayList;
/**
 *
 * @author Nikos
 */
public class Deletion_Promithies_MedEq extends javax.swing.JFrame {

    /**
     * Creates new form Deletion_Promithies_MedEq
     */
    private ArrayList<String> medList = new ArrayList();
    private ArrayList<String> medEqList = new ArrayList();
    private ArrayList<String> medQuantityList = new ArrayList();
    private ArrayList<String> medEqQuantityList = new ArrayList();
    
    
    private int available_space;
    public Deletion_Promithies_MedEq() {
        initComponents();
    }
        public Deletion_Promithies_MedEq(int available_space,ArrayList<String> medList, ArrayList<String> medEqList,ArrayList<String> medQuantityList,ArrayList<String> medEqQuantityList) {
        this.available_space = available_space;
        this.medList = medList;
        this.medEqList = medEqList;
        this.medEqQuantityList = medEqQuantityList;
        this.medQuantityList = medQuantityList;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conditionalMsg1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deletionMedEqList = new javax.swing.JList<>();
        delButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conditionalMsg1.setBackground(new java.awt.Color(153, 204, 255));
        conditionalMsg1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        deletionMedEqList.setModel(new javax.swing.DefaultListModel<String>());
        {
            javax.swing.DefaultListModel<String> ml = (javax.swing.DefaultListModel<String>)deletionMedEqList.getModel();

            for(int i=0;i<medEqList.size(); i++){
                ml.addElement(medEqList.get(i));
            }
        }
        jScrollPane1.setViewportView(deletionMedEqList);

        delButton.setText("Διαγραφή");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        backButton.setText("Τέλος");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conditionalMsg1Layout = new javax.swing.GroupLayout(conditionalMsg1);
        conditionalMsg1.setLayout(conditionalMsg1Layout);
        conditionalMsg1Layout.setHorizontalGroup(
            conditionalMsg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conditionalMsg1Layout.createSequentialGroup()
                .addGroup(conditionalMsg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conditionalMsg1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(delButton))
                    .addGroup(conditionalMsg1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conditionalMsg1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        conditionalMsg1Layout.setVerticalGroup(
            conditionalMsg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conditionalMsg1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(delButton)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conditionalMsg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conditionalMsg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        Dashboard_Promithies dp = new Dashboard_Promithies(); 
        Conditional_Message cm = new Conditional_Message(dp);
        try{
        int selected = deletionMedEqList.getSelectedIndex();
        medEqList.remove(selected);
        
        available_space = available_space + Integer.parseInt(medEqQuantityList.get(selected));
        cm.triggerMsg("Διαγραφή Επιτυχής!");
        cm.setVisible(true);
        Deletion_Promithies_MedEq dpm = new Deletion_Promithies_MedEq(available_space,medList,medEqList,medQuantityList,medEqQuantityList);
        dp.dispose();
        dispose();
        dpm.setVisible(true);
        } catch (java.lang.IndexOutOfBoundsException exc){
            cm.triggerMsg("Δεν υπάρχουν στοιχεία για διαγραφή!");
            cm.setVisible(true);
        }
    }//GEN-LAST:event_delButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Dashboard_Promithies dp = new Dashboard_Promithies(available_space, medList,medEqList,medQuantityList,medEqQuantityList);
        dispose();
        dp.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deletion_Promithies_MedEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deletion_Promithies_MedEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deletion_Promithies_MedEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deletion_Promithies_MedEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deletion_Promithies_MedEq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel conditionalMsg1;
    private javax.swing.JButton delButton;
    private javax.swing.JList<String> deletionMedEqList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
