/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmp_gui;
import java.util.ArrayList;
import data.*;
import java.util.Calendar;
/**
 *
 * @author Theodoros Tomadakis
 */
public class Enhmerwsh_Efhmerias extends javax.swing.JFrame{

    
    private Dashboard_Headdoc dashboard; //pernw stigmuotypo tou dashboard toy headdoc_dashboard
    ArrayList<String> JComboList = new ArrayList<String>(200); //prosorini lista gia to jcombo
    
    public Enhmerwsh_Efhmerias(Dashboard_Headdoc dashboard) {
        this.dashboard = dashboard;
        initComponents();
    }
    
    //emfanisei tis efhmeries sto jcombo
    public void InitPersonList(){ 
        ArrayList<OnCall> TempOCList = dashboard.returnOnCalls(); //pernw tis efhmeries apo to dashboard headdoc
        jComboBox1.removeAllItems(); // kanw remove ola ta items sta jcombo
        ArrayList<String>tempOnomaList = new ArrayList<String>(10); //prosorinoi pinakes gia na diasfalisw oti to amka
        ArrayList<String>tempAmkaList = new ArrayList<String>(10); //kai to onoma tha einai unique
        String amka = String.valueOf(TempOCList.get(0).getAMKAOnCall()); //pernw to prwto amka 
        String onoma = TempOCList.get(0).getOnCallDoc().getName(); //kai to prwto onoma 
        tempOnomaList.add(onoma); // ta prosthetw stous antistoixous pinakes
        tempAmkaList.add(amka);
        this.JComboList.add("Όνομα: " + onoma + "    " + "AMKA: " + amka); //to prosthetw sto jcombo
        for (int i = 1; i<TempOCList.size(); i++){
            amka = String.valueOf(TempOCList.get(i).getAMKAOnCall()); //pernume to epomeno amka kai
            onoma = TempOCList.get(i).getOnCallDoc().getName(); //onoma giatrwn twn efhmeriwn 
            if ((!tempOnomaList.contains(onoma)) && (!tempAmkaList.contains(amka))){ // elegxoyme an yparxoun ston proswrino pinaka
                tempOnomaList.add(onoma); //an oxi ta prosthetume 
                tempAmkaList.add(amka);
                this.JComboList.add("Όνομα: " + onoma + "    " + "AMKA: " + amka); //ta prosthetume kai sto jcombo
            }
        }                    
    }

    
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enhmerwsh_Efhmerias = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        this.InitPersonList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        change_value_msg = new javax.swing.JLabel();
        change_value_msg1 = new javax.swing.JLabel();
        change_value_msg2 = new javax.swing.JLabel();
        Hmera = new javax.swing.JComboBox<>();
        Mhnas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Προσθήκη εφημερίας");

        Enhmerwsh_Efhmerias.setBackground(new java.awt.Color(153, 204, 255));
        Enhmerwsh_Efhmerias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Προσθήκη εφημερίας", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Επιλέξτε άτομο:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ορίστε νέα ημ/νια:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<String>());
        javax.swing.DefaultComboBoxModel<String> person_list_model = (javax.swing.DefaultComboBoxModel<String>)jComboBox1.getModel();
        for(int x=0; x<JComboList.size();x++){
            person_list_model.addElement(JComboList.get(x));
        }

        jButton1.setText("Προσθήκη εφημερίας");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Έξοδος");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        change_value_msg.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        change_value_msg.setForeground(new java.awt.Color(255, 255, 255));
        change_value_msg.setText("Ημέρα:");

        change_value_msg1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        change_value_msg1.setForeground(new java.awt.Color(255, 255, 255));
        change_value_msg1.setText("Επιλέξτε τα στοιχεία που επιθυμείτε:");

        change_value_msg2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        change_value_msg2.setForeground(new java.awt.Color(255, 255, 255));
        change_value_msg2.setText("Μήνας:");

        Hmera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        Mhnas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        javax.swing.GroupLayout Enhmerwsh_EfhmeriasLayout = new javax.swing.GroupLayout(Enhmerwsh_Efhmerias);
        Enhmerwsh_Efhmerias.setLayout(Enhmerwsh_EfhmeriasLayout);
        Enhmerwsh_EfhmeriasLayout.setHorizontalGroup(
            Enhmerwsh_EfhmeriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enhmerwsh_EfhmeriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Enhmerwsh_EfhmeriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Enhmerwsh_EfhmeriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Enhmerwsh_EfhmeriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enhmerwsh_EfhmeriasLayout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(change_value_msg1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(Enhmerwsh_EfhmeriasLayout.createSequentialGroup()
                        .addComponent(change_value_msg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Hmera, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(change_value_msg2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mhnas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        Enhmerwsh_EfhmeriasLayout.setVerticalGroup(
            Enhmerwsh_EfhmeriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enhmerwsh_EfhmeriasLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(change_value_msg1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Enhmerwsh_EfhmeriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Enhmerwsh_EfhmeriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(change_value_msg)
                        .addComponent(change_value_msg2))
                    .addComponent(Hmera)
                    .addComponent(Mhnas))
                .addGap(22, 22, 22)
                .addGroup(Enhmerwsh_EfhmeriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(Enhmerwsh_EfhmeriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Enhmerwsh_Efhmerias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Enhmerwsh_Efhmerias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //eksodos sth lista efhmeriwn tou arxikou parathirou
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dashboard.setEnabled(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

// elegxos an borei na prostehei h efhmeria, epistrefei true an borei    
public boolean addToHDJList(ArrayList<OnCall> e, int amka, String cdate){ //kanei update ton pinaka tou HeadDoc_Dashboard
    boolean bool = false;
    e = dashboard.getClinic().getOnCallList(); //pernume thn oncall list
    int k = 0; //metrhths gia diaforetikes hmeromnies
    int j = 0; //metrhths gia diaforetikes efhmeries tou idiou atomoy
    for (int i = 0; i<e.size(); i++){
        if (dashboard.getClinic().checkOnCallDate(e.get(i).getOnCallDate(),cdate)){ //elegxoyme an sumpeftei h efhmeria
            k++;
        }
        if (amka == e.get(i).getAMKAOnCall()){
            j++; //oi efhmeries poy exei to kathe atomo
        }
    }
    
    ArrayList<Doctor> tempDocList = dashboard.returnDocList(); //pernume th lista giatrwn apo to headdoc_dashboard
    String name =" "; //prosorini arxikopoihsh
    Doctor d1 = null;
    for (int i = 0; i < tempDocList.size(); i++){
        if (amka == tempDocList.get(i).getAMKA()){//apo to amka, vruskume to onoma
            name = tempDocList.get(i).getName();
            d1 = new Doctor (amka, name, tempDocList.get(i).getSpeciality(), dashboard.getClinic()); //arxikopoihsh neou adikeimenoy giatrou
        }
    }
    if (k == (e.size())){//an kamia efhmeia de sumpeftei me authi pou thelume na prosthesume
        bool = true;
        if (j==0){//an to atomo den exei kamia efhmeria
            OnCall tempOC = new OnCall(cdate, d1, dashboard.getClinic().getClinicName(), j); //arxikopoihsh neas efhmerias
            e.add(tempOC);//thn prostheto sti lista efhmeriwn ths kliniks
            dashboard.JOnCall_list_str.add("Ημερομηνία: " + cdate + "   " + "Όνομα Γιατρού: " + name + "    " +  "ΑΜΚΑ Γιατρού: " + amka + "   " + "Κλινική: " + dashboard.getClinic().getClinicName() + "   " + "Αριθμός Εφημερίας: " + 1); //to string poy prostithetai sto jlist tou headdoc_dashboard
        }else{// ta idia me panw me mony diafora oti to j auksanetai kata 1 gia th nea efhmeria
            OnCall tempOC = new OnCall(cdate, d1, dashboard.getClinic().getClinicName(), j+1 ); 
            e.add(tempOC);
            dashboard.JOnCall_list_str.add("Ημερομηνία: " + cdate + "   " + "Όνομα Γιατρού: " + name + "    " +  "ΑΜΚΑ Γιατρού: " + amka + "   " + "Κλινική: " + dashboard.getClinic().getClinicName() + "   " + "Αριθμός Εφημερίας: " + (j+1));
        }
        return bool; //epistrepse true
    }else return bool;
}

    //prosthiki ths efhmeria sto jlist tou headdoc_dashboard
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String temp1 = Hmera.getItemAt(Hmera.getSelectedIndex()); // pairnoyme tis times apo ta jcombo
        String temp2 = Mhnas.getItemAt(Mhnas.getSelectedIndex());
        int year = Calendar.getInstance().get(Calendar.YEAR); //pairnoyme to xrono
        String tempDate = temp1 + "/" + temp2 + "/" + String.valueOf(year); //thetume tin imeromhnia opws tin exoume sto formatter tou clinic
        
        //oi times tha einai panta egkures afou tis epilegei apo to jcombobox
        String tempS = jComboBox1.getItemAt(jComboBox1.getSelectedIndex()); //briskoyme to amka tis epiloghs toy jcombo
        String tempAMKA = tempS.substring(tempS.lastIndexOf(":")+2, (tempS.length()));//dhmiourgoume substring gia na to kanume auto
        int intAMKA = Integer.parseInt(tempAMKA); //kanume to amka int 
        if (this.addToHDJList(dashboard.returnOnCalls(), intAMKA, tempDate)){//kalume gia na dume an borume na kanyme update to array list
            javax.swing.DefaultListModel<String>  oncall_jlist_model = (javax.swing.DefaultListModel<String>)dashboard.getOnCall_list().getModel(); //pernume to modelo ths jlist toy dashboard_headdoc
            oncall_jlist_model.addElement(dashboard.JOnCall_list_str.get(dashboard.JOnCall_list_str.size()-1));//edw ginetai h orath enhmerwsh tis listas 
            Conditional_Message con1 = new Conditional_Message(this);
            con1.triggerMsg("<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Επιτυχία προσθήκης εφημερίας!</html>");
            con1.setVisible(true);
            this.setEnabled(false);
        }else{
            Conditional_Message con1 = new Conditional_Message(this); //dhmiourgoyme minima error
            con1.triggerMsg("<html>Η εφημερία που επιχειρήσατε να προσθέσετε υπάρχει ήδη στη λίστα. Παρακαλώ δώστε νέα ημερομηνία.</html>"); //to minima 
            con1.setVisible(true);
            this.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enhmerwsh_Efhmerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enhmerwsh_Efhmerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enhmerwsh_Efhmerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enhmerwsh_Efhmerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Enhmerwsh_Efhmerias;
    private javax.swing.JComboBox<String> Hmera;
    private javax.swing.JComboBox<String> Mhnas;
    private javax.swing.JLabel change_value_msg;
    private javax.swing.JLabel change_value_msg1;
    private javax.swing.JLabel change_value_msg2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
