package hmp_gui;
import java.util.ArrayList;
import data.*;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Thodoris Tomadakis
 */

public class Enhmerwsh_Yparxoysas_Efhmerias extends javax.swing.JFrame {

    private Dashboard_Headdoc dashboard; 
    private int oncall_index;
    private OnCall oc1 = null;
    
    public Enhmerwsh_Yparxoysas_Efhmerias(Dashboard_Headdoc dashboard,OnCall oc, int oc_index) {
        this.dashboard = dashboard;
        oncall_index = oc_index;
        oc1 = oc;
        initComponents();
    }
    
    public String Spinner1(){// pairnei thn timh toy jspinner1, epistrefei 01 an bei mh egkurh timh (pros to paron)
        try {
            jSpinner2.commitEdit();
        } catch (ParseException e) {e.printStackTrace();}
        javax.swing.SpinnerNumberModel s11 = (javax.swing.SpinnerNumberModel)this.jSpinner2.getModel();
        int tempValue = (Integer)s11.getValue();
        if (tempValue <=0 || tempValue > 30){
            Conditional_Message con1 = new Conditional_Message(this);
            con1.triggerMsg("Η ημέρα που επιλέξατε δεν είναι έγκυρη");
            con1.setVisible(true);
            this.setEnabled(false);
        }
        String temp=" ";
        if (tempValue>0 && tempValue <=30){
            switch (tempValue){
                case 1:
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                  String s1 = String.valueOf(0);
                  String s2 = String.valueOf(tempValue);
                  temp = s1.concat(s2);
                  break;
                default:
                  temp = String.valueOf(tempValue);
            }
            return temp;
        }else return "error";
    }
    
    public String Spinner2(){ //pairnei thn timh toy jspinner2
        try {
            jSpinner1.commitEdit();
        } catch (ParseException e) {e.printStackTrace();}
        javax.swing.SpinnerNumberModel s12 = (javax.swing.SpinnerNumberModel)this.jSpinner1.getModel();
        int tempValue = (Integer)s12.getValue();
        if (tempValue <=0 || tempValue > 12){
            Conditional_Message con1 = new Conditional_Message(this);
            con1.triggerMsg("O μήνας που επιλέξατε δεν είναι έγκυρος");
            con1.setVisible(true);
            this.setEnabled(false);
        }
        String temp=" ";
        if (tempValue>0 && tempValue <=12){
            switch (tempValue){
                case 1:
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                  String s1 = String.valueOf(0);
                  String s2 = String.valueOf(tempValue);
                  temp = s1.concat(s2);
                  break;
                default:
                  temp = String.valueOf(tempValue);
            }
            return temp;
        }else return "error";
    }
    
    public void ShowOnCallInfo(OnCall oc1){      
        String amka = Integer.toString(oc1.getAMKAOnCall());
        hm.setText(oc1.getOnCallDate());
        amka11.setText(amka);
        onoma.setText(oc1.getOnCallDoc());
        klin.setText(dashboard.Clinic1.getClinicName());
        ar.setText(Integer.toString(oc1.getNum_OnCall()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        amka11 = new javax.swing.JTextArea();
        onoma = new javax.swing.JTextArea();
        klin = new javax.swing.JTextArea();
        ar = new javax.swing.JTextArea();
        hm = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        change_value_msg = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        SpinnerNumberModel s12 = new SpinnerNumberModel(1, 1, 12, 1);
        jSpinner2 = new JSpinner(s12);
        change_value_msg2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        SpinnerNumberModel s11 = new SpinnerNumberModel(1, 1, 30, 1);
        jSpinner1 = new JSpinner(s11);
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ενημέρωση υπάρχουσας εφημερίας"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Τρέχουσα ημ/νια:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Όνομα Γιατρού:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Κλινική:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Αριθμός εφημερίας:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ΑΜΚΑ Γιατρού:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Στοιχεία Εφημερίας:");

        amka11.setEditable(false);
        amka11.setColumns(20);
        amka11.setRows(5);

        onoma.setEditable(false);
        onoma.setColumns(20);
        onoma.setRows(5);

        klin.setEditable(false);
        klin.setColumns(20);
        klin.setRows(5);

        ar.setEditable(false);
        ar.setColumns(20);
        ar.setRows(5);

        hm.setEditable(false);
        hm.setColumns(20);
        hm.setRows(5);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ορίστε νέα ημ/νία:");

        change_value_msg.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        change_value_msg.setForeground(new java.awt.Color(255, 255, 255));
        change_value_msg.setText("Ημέρα:");

        change_value_msg2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        change_value_msg2.setForeground(new java.awt.Color(255, 255, 255));
        change_value_msg2.setText("Μήνας:");

        jButton1.setText("Ενημέρωση εφημερίας");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(change_value_msg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(change_value_msg2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(141, 141, 141)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(onoma, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(amka11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(klin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(onoma, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amka11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(klin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(change_value_msg)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_value_msg2)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String temp1 = Spinner1();
        String temp2 = Spinner2();
        int year = Calendar.getInstance().get(Calendar.YEAR); 
        String tempDate = temp1 + "/" + temp2 + "/" + String.valueOf(year); 
        ArrayList <OnCall> e = dashboard.Clinic1.getOnCallList();
        int k = 0;
        if (tempDate == oc1.getOnCallDate()){
            Conditional_Message con1 = new Conditional_Message(this);
            con1.triggerMsg("Η ημερομηνία που επιλέξατε είναι η ίδια!");
            con1.setVisible(true);
            this.setEnabled(false);
        }
        for (int i = 0; i<e.size(); i++){
            if (dashboard.Clinic1.checkOnCallDate(e.get(i).getOnCallDate(),tempDate)){
                k++;
            }
            if(k == e.size()){
                oc1.setOnCallDate(tempDate);
                String s1 = "Ημερομηνία: " + tempDate + "   " + "Όνομα Γιατρού: " + oc1.getOnCallDoc() + "    " +  "ΑΜΚΑ Γιατρού: " + oc1.getAMKAOnCall() + "   " + "Κλινική: " + dashboard.Clinic1.getClinicName() + "   " + "Αριθμός Εφημερίας: " + oc1.getNum_OnCall();
                javax.swing.DefaultListModel<String>  oncall_jlist_model = (javax.swing.DefaultListModel<String>)dashboard.getOnCall_list().getModel(); //pernume to modelo ths jlist toy dashboard_headdoc
                oncall_jlist_model.set(this.oncall_index,s1);
            }else{
                Conditional_Message con1 = new Conditional_Message(this);
                con1.triggerMsg("Η ημερομηνία που επιλέξατε συμπέφτει πάνω σε άλλες!");
                con1.setVisible(true);
                this.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enhmerwsh_Yparxoysas_Efhmerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enhmerwsh_Yparxoysas_Efhmerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enhmerwsh_Yparxoysas_Efhmerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enhmerwsh_Yparxoysas_Efhmerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {}
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea amka11;
    private javax.swing.JTextArea ar;
    private javax.swing.JLabel change_value_msg;
    private javax.swing.JLabel change_value_msg2;
    private javax.swing.JTextArea hm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea klin;
    private javax.swing.JTextArea onoma;
    private javax.swing.JTextArea patient_amka4;
    private javax.swing.JTextArea patient_amka5;
    private javax.swing.JTextArea patient_amka6;
    private javax.swing.JTextArea patient_amka7;
    // End of variables declaration//GEN-END:variables
}
