/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hmp_gui;

import java.util.ArrayList;
import data.PatientMedicine;
import data.Patient;
import data.Doctor;
import java.util.Date;
/**
 *
 * @author John
 */
public class Nosileutis_Farmaka extends javax.swing.JFrame {

    /* Creates new form Nosileutis_Farmaka */
    
    private ArrayList<PatientMedicine> tmpMedList = new ArrayList();
    private ArrayList<String> medTaken = new ArrayList();
    private ArrayList<String> medList = new ArrayList(500);
    Doctor doc = new Doctor();
    Patient pat = new Patient();
    
    Date date = new Date();
    //Dashboard_Nosileutis dn = new Dashboard_Nosileutis();
    public Nosileutis_Farmaka(){
        initComponents();
    }
    public Nosileutis_Farmaka(Patient patient) {
        this.pat = patient;
        
        initComponents();
    }
    public Nosileutis_Farmaka(Patient patient,ArrayList<String> medTaken) {
        this.pat = patient;
        this.medTaken = medTaken;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        med_info = new javax.swing.JPanel();
        MedsDisp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pat_list = new javax.swing.JList<>();
        EditButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        med_info.setBackground(new java.awt.Color(153, 204, 255));
        med_info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        MedsDisp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MedsDisp.setForeground(new java.awt.Color(255, 255, 255));
        MedsDisp.setText("Φάρμακα Ασθενή και ένδειξη λήψης φαρμάκων");

        this.InitMeds();
        pat_list.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pat_list.setModel(new javax.swing.DefaultListModel<String>() {
        });
        {
            javax.swing.DefaultListModel<String> pl = (javax.swing.DefaultListModel<String>)pat_list.getModel();
            for (int i=0;i<medList.size();i++){
                pl.addElement(medList.get(i));
                pl.addElement("");
                //if (medTaken.size() != 0) {
                    pl.addElement(medTaken.get(i));
                    //}
            }
        }
        jScrollPane2.setViewportView(pat_list);

        EditButton.setText("Αλλαγή ένδειξης");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        prevButton.setText("Πίσω");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout med_infoLayout = new javax.swing.GroupLayout(med_info);
        med_info.setLayout(med_infoLayout);
        med_infoLayout.setHorizontalGroup(
            med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(med_infoLayout.createSequentialGroup()
                .addGroup(med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(med_infoLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(MedsDisp))
                    .addGroup(med_infoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(med_infoLayout.createSequentialGroup()
                                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, med_infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prevButton)
                .addGap(23, 23, 23))
        );
        med_infoLayout.setVerticalGroup(
            med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(med_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prevButton)
                .addGap(5, 5, 5)
                .addComponent(MedsDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditButton)
                    .addComponent(refreshButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(med_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(med_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        //enum_list.setVisible(false);
        medTaken.clear();
        //dispose();
        for (int i=0; i<tmpMedList.size();i++){
            medTaken.add("");
            nosileutis_medCheck nmc = new nosileutis_medCheck(pat.getName(),tmpMedList.get(i).getName(),medTaken,i);
            nmc.setVisible(true);
            //medTaken.add(nmc.isChecked());
            //System.out.println(nmc.isChecked());
        }
    
    }//GEN-LAST:event_EditButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        Dashboard_Nosileutis dn = new Dashboard_Nosileutis();
        dispose();
        dn.setVisible(true);
    }//GEN-LAST:event_prevButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        dispose();
        Nosileutis_Farmaka nf = new Nosileutis_Farmaka(pat,medTaken);
        nf.setVisible(true);
    }//GEN-LAST:event_refreshButtonActionPerformed

    
    
    public void InitMeds(){
        
        PatientMedicine pm1 = new PatientMedicine(pat.getName(),pat,"Zanax", "Ηρεμιστικό","1 χάπι ανά 8 ώρες","Αδυναμία",101);
        PatientMedicine pm2 = new PatientMedicine(pat.getName(),pat,"Depon", "Pausipono","2 χάπια ανά 8 ώρες","-",101);
        PatientMedicine pm3 = new PatientMedicine(pat.getName(),pat,"Algofren", "Παυσίπονο","1 χάπι ανά 8 ώρες","-",1);
        
        
        
        tmpMedList.add(pm1);
        tmpMedList.add(pm2);
        tmpMedList.add(pm3);
        
        
        medList.clear();
        
        for (int i=0; i<tmpMedList.size();i++){
            medTaken.add("Δεν έλαβε το φάρμακο" + "         " + date);
            medList.add("Medicine: " + tmpMedList.get(i).getName() + "      Type: " + tmpMedList.get(i).getType() + "      Recommended dosage: " + tmpMedList.get(i).getDosage() + "      Side effects: " + tmpMedList.get(i).getSideEffects());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_Farmaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_Farmaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_Farmaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_Farmaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nosileutis_Farmaka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel MedsDisp;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel med_info;
    private javax.swing.JList<String> pat_list;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables

}
