/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmp_gui;
import data.Patient;
import data.PatientMedicine;
import java.util.ArrayList;
/**
 *
 * @author John
 */
public class nosileutis_medCheck extends javax.swing.JFrame {

    /**
     * Creates new form nosileutis_medCheck
     */
    private String p,pm;
    
    private boolean checked;
    ArrayList<String> kati = new ArrayList(20);
    public nosileutis_medCheck(String p,String pm) {
        this.p = p;
        this.pm = pm;
        initComponents();
        
    }
    public nosileutis_medCheck() {
        initComponents();
    }
    public boolean isChecked(){
        return checked;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        med_info = new javax.swing.JPanel();
        CheckButtonNo = new javax.swing.JButton();
        CheckButtonYes = new javax.swing.JButton();
        question = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        med_info.setBackground(new java.awt.Color(153, 204, 255));
        med_info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        CheckButtonNo.setText("No");
        CheckButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonNoActionPerformed(evt);
            }
        });

        CheckButtonYes.setText("Yes");
        CheckButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonYesActionPerformed(evt);
            }
        });

        question.setBackground(new java.awt.Color(153, 204, 255));
        question.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        question.setForeground(new java.awt.Color(255, 255, 255));
        question.setText("Ο " + this.p + " έλαβε το φάρμακο " + this.pm + ";");

        javax.swing.GroupLayout med_infoLayout = new javax.swing.GroupLayout(med_info);
        med_info.setLayout(med_infoLayout);
        med_infoLayout.setHorizontalGroup(
            med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(med_infoLayout.createSequentialGroup()
                .addGroup(med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(med_infoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(CheckButtonNo)
                        .addGap(269, 269, 269)
                        .addComponent(CheckButtonYes))
                    .addGroup(med_infoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        med_infoLayout.setVerticalGroup(
            med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(med_infoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckButtonNo)
                    .addComponent(CheckButtonYes))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(med_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(med_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonYesActionPerformed
        this.checked = true;
        System.out.println(pm);
        dispose();
    }//GEN-LAST:event_CheckButtonYesActionPerformed

    private void CheckButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonNoActionPerformed
        this.checked = false;
        System.out.println(p);
        dispose();
    }//GEN-LAST:event_CheckButtonNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nosileutis_medCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nosileutis_medCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nosileutis_medCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nosileutis_medCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nosileutis_medCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckButtonNo;
    private javax.swing.JButton CheckButtonYes;
    private javax.swing.JPanel med_info;
    private javax.swing.JTextField question;
    // End of variables declaration//GEN-END:variables
}
