/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hmp_gui;

import java.util.ArrayList;
import data.PatientMedicine;
import data.Patient;
import data.Doctor;
/**
 *
 * @author John
 */
public class Nosileutis_Farmaka extends javax.swing.JFrame {

    /* Creates new form Nosileutis_Farmaka */
    
    ArrayList<PatientMedicine> tmpMedList = new ArrayList();
    ArrayList<Boolean> medTaken = new ArrayList();
    ArrayList<String> medList = new ArrayList(500);
    Doctor doc = new Doctor();
    Patient pat = new Patient();
    //Dashboard_Nosileutis dn = new Dashboard_Nosileutis();
    public Nosileutis_Farmaka(){}
    public Nosileutis_Farmaka(Patient patient) {
        //this.dn = dash;
        this.pat = patient;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        med_info = new javax.swing.JPanel();
        MedsDisp = new javax.swing.JLabel();
        EnumDisp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enum_list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        pat_list = new javax.swing.JList<>();
        EditButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        med_info.setBackground(new java.awt.Color(153, 204, 255));
        med_info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        MedsDisp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MedsDisp.setForeground(new java.awt.Color(255, 255, 255));
        MedsDisp.setText("Φάρμακα Ασθενή");

        EnumDisp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        EnumDisp.setForeground(new java.awt.Color(255, 255, 255));
        EnumDisp.setText("Ένδειξη λήψης φαρμάκων");

        enum_list.setModel(new javax.swing.DefaultListModel<String>() {
        });
        {

            javax.swing.DefaultListModel<String> l = (javax.swing.DefaultListModel<String>) enum_list.getModel();
            for (int i=0;i<medTaken.size();i++){
                if(medTaken.get(i)){
                    l.addElement("Έλαβε");
                    l.addElement("");
                }
                else{
                    l.addElement("Δεν έλαβε");
                    l.addElement("");
                }
            }
        }
        jScrollPane1.setViewportView(enum_list);

        this.InitMeds();
        pat_list.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pat_list.setModel(new javax.swing.DefaultListModel<String>() {
        });
        {
            javax.swing.DefaultListModel<String> pl = (javax.swing.DefaultListModel<String>)pat_list.getModel();
            for (int i=0;i<medList.size();i++){
                pl.addElement(medList.get(i));
                pl.addElement("");
            }
        }
        jScrollPane2.setViewportView(pat_list);

        EditButton.setText("Αλλαγή ένδειξης");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        prevButton.setText("Πίσω");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout med_infoLayout = new javax.swing.GroupLayout(med_info);
        med_info.setLayout(med_infoLayout);
        med_infoLayout.setHorizontalGroup(
            med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, med_infoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MedsDisp)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnumDisp)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, med_infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prevButton)
                .addGap(23, 23, 23))
        );
        med_infoLayout.setVerticalGroup(
            med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(med_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prevButton)
                .addGap(42, 42, 42)
                .addGroup(med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedsDisp)
                    .addComponent(EnumDisp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(med_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditButton)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(med_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(med_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        //enum_list.setVisible(false);
        medTaken.clear();
        for (int i=0; i<tmpMedList.size();i++){
            nosileutis_medCheck nmc = new nosileutis_medCheck(pat.getName(),tmpMedList.get(i).getName());
            nmc.setVisible(true);
            medTaken.add(nmc.isChecked());
            //System.out.println(nmc.isChecked());
            
            
        }
    
    }//GEN-LAST:event_EditButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        Dashboard_Nosileutis dn = new Dashboard_Nosileutis();
        dispose();
        dn.setVisible(true);
    }//GEN-LAST:event_prevButtonActionPerformed

    
    
    public void InitMeds(){
        
        PatientMedicine pm1 = new PatientMedicine(pat.getName(),pat,"Zanax", "Hremistiko","1 xapi ana 8 wres","adunamia",101);
        PatientMedicine pm2 = new PatientMedicine(pat.getName(),pat,"Depon", "Pausipono","2 xapia ana 8 wres","-",101);
        PatientMedicine pm3 = new PatientMedicine(pat.getName(),pat,"A medicine", "Type","recommended dosage","side effects",1);
        
        
        
        tmpMedList.add(pm3);
        tmpMedList.add(pm2);
        tmpMedList.add(pm1);
        
        
        medList.clear();
        
        for (int i=0; i<tmpMedList.size();i++){
            medList.add("Medicine: " + tmpMedList.get(i).getName() + "      Type: " + tmpMedList.get(i).getType() +         "Recommended dosage: " + tmpMedList.get(i).getDosage() + "      Side effects: " + tmpMedList.get(i).getSideEffects());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_Farmaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_Farmaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_Farmaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_Farmaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nosileutis_Farmaka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel EnumDisp;
    private javax.swing.JLabel MedsDisp;
    private javax.swing.JList<String> enum_list;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel med_info;
    private javax.swing.JList<String> pat_list;
    private javax.swing.JButton prevButton;
    // End of variables declaration//GEN-END:variables

}
