/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmp_gui;

import data.Patient;
/**
 *
 * @author John
 */
public class Nosileutis_PatProfile extends javax.swing.JFrame {

    /**
     * Creates new form Nosileutis_PatProfile
     */
    
    Patient pat = new Patient();
    public Nosileutis_PatProfile(Patient pat) {
        this.pat = pat;
        initComponents();
    }
    public Nosileutis_PatProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Greetings = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        pat_info = new javax.swing.JPanel();
        nameTag = new javax.swing.JLabel();
        Greetings2 = new javax.swing.JLabel();
        supervised_byTag = new javax.swing.JLabel();
        amkaTag = new javax.swing.JLabel();
        ageTag = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicalHistoryList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientHistoryList = new javax.swing.JList<>();
        medicalHistoryTag = new javax.swing.JLabel();
        conditionTag = new javax.swing.JLabel();
        patientHistoryTag = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        amkaField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        supervised_byField = new javax.swing.JTextField();
        statusField = new javax.swing.JTextField();

        Greetings.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Greetings.setForeground(new java.awt.Color(255, 255, 255));
        Greetings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greetings.setText("<html>Καλώς Ορίσατε στο Πρόγραμμα<br>&nbsp;&nbsp;&nbsp;&nbsp;Διαχείρισης Νοσοκομείων!</html>");
        Greetings.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pat_info.setBackground(new java.awt.Color(153, 204, 255));
        pat_info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        nameTag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTag.setForeground(new java.awt.Color(255, 255, 255));
        nameTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameTag.setText("Όνομα:");
        nameTag.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        Greetings2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Greetings2.setForeground(new java.awt.Color(255, 255, 255));
        Greetings2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greetings2.setText("<html>Πληροφορίες Ασθενή</html>");
        Greetings2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        supervised_byTag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supervised_byTag.setForeground(new java.awt.Color(255, 255, 255));
        supervised_byTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supervised_byTag.setText("Υπεύθυνος Γιατρός:");
        supervised_byTag.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        amkaTag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amkaTag.setForeground(new java.awt.Color(255, 255, 255));
        amkaTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amkaTag.setText("ΑΜΚΑ:");
        amkaTag.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        ageTag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageTag.setForeground(new java.awt.Color(255, 255, 255));
        ageTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageTag.setText("Ηλικία:");
        ageTag.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        medicalHistoryList.setModel(new javax.swing.DefaultListModel<String>()
        );
        {
            javax.swing.DefaultListModel<String> medicalL = (javax.swing.DefaultListModel<String>)medicalHistoryList.getModel();
            medicalL.addElement(pat.getConditions());
        }
        jScrollPane1.setViewportView(medicalHistoryList);

        patientHistoryList.setModel(new javax.swing.DefaultListModel<String>()
        );
        {
            javax.swing.DefaultListModel<String> historyL = (javax.swing.DefaultListModel<String>)patientHistoryList.getModel();
            historyL.addElement(pat.getHistory());
        }
        jScrollPane2.setViewportView(patientHistoryList);

        medicalHistoryTag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        medicalHistoryTag.setForeground(new java.awt.Color(255, 255, 255));
        medicalHistoryTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicalHistoryTag.setText("Ιστορικό παθήσεων:");
        medicalHistoryTag.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        conditionTag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conditionTag.setForeground(new java.awt.Color(255, 255, 255));
        conditionTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conditionTag.setText("Κατάσταση Ασθενή:");
        conditionTag.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        patientHistoryTag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patientHistoryTag.setForeground(new java.awt.Color(255, 255, 255));
        patientHistoryTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientHistoryTag.setText("Ιστορικό Ασθενή:");
        patientHistoryTag.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameField.setText(pat.getName());
        {
            nameField.setEditable(false);
        }
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        amkaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amkaField.setText(Integer.toString(pat.getAmka()));
        {
            amkaField.setEditable(false);
        }
        amkaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amkaFieldActionPerformed(evt);
            }
        });

        ageField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ageField.setText(Integer.toString(pat.getAge()));
        {
            ageField.setEditable(false);
        }
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });

        supervised_byField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        supervised_byField.setText(pat.getSupervisedBy().getName());
        {
            supervised_byField.setEditable(false);
        }
        supervised_byField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervised_byFieldActionPerformed(evt);
            }
        });

        statusField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusField.setText(pat.getStatus());
        {
            statusField.setEditable(false);
        }
        statusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pat_infoLayout = new javax.swing.GroupLayout(pat_info);
        pat_info.setLayout(pat_infoLayout);
        pat_infoLayout.setHorizontalGroup(
            pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pat_infoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pat_infoLayout.createSequentialGroup()
                        .addComponent(ageTag, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pat_infoLayout.createSequentialGroup()
                        .addComponent(amkaTag, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amkaField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pat_infoLayout.createSequentialGroup()
                        .addComponent(supervised_byTag, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supervised_byField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pat_infoLayout.createSequentialGroup()
                        .addComponent(conditionTag, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pat_infoLayout.createSequentialGroup()
                        .addComponent(nameTag, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pat_infoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(patientHistoryTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(medicalHistoryTag, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pat_infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pat_infoLayout.createSequentialGroup()
                        .addComponent(Greetings2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pat_infoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        pat_infoLayout.setVerticalGroup(
            pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pat_infoLayout.createSequentialGroup()
                .addComponent(Greetings2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amkaTag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amkaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supervised_byTag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supervised_byField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conditionTag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientHistoryTag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalHistoryTag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pat_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pat_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pat_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void amkaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amkaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amkaFieldActionPerformed

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void supervised_byFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervised_byFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supervised_byFieldActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_PatProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_PatProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_PatProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nosileutis_PatProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nosileutis_PatProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Greetings;
    private javax.swing.JLabel Greetings2;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageTag;
    private javax.swing.JTextField amkaField;
    private javax.swing.JLabel amkaTag;
    private javax.swing.JLabel conditionTag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JList<String> medicalHistoryList;
    private javax.swing.JLabel medicalHistoryTag;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameTag;
    private javax.swing.JPanel pat_info;
    private javax.swing.JList<String> patientHistoryList;
    private javax.swing.JLabel patientHistoryTag;
    private javax.swing.JTextField statusField;
    private javax.swing.JTextField supervised_byField;
    private javax.swing.JLabel supervised_byTag;
    // End of variables declaration//GEN-END:variables
}
